BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "edgeos"
BBFILE_PATTERN_edgeos = "^${LAYERDIR}/"
BBFILE_PRIORITY_edgeos = "10"

LAYERDEPENDS_edgeos = "core fsl-bsp-release fsl-sdk-release"
LAYERSERIES_COMPAT_edgeos = "scarthgap"
